### ISSUE TITLE
[Feature] 방 목록 셀 클릭시 해당 방으로 이동하는 기능 추가

### ISSUE THREAD

**Issue by taek0622** [DeveloperAcademy-POSTECH/MacC-Team-Samsamhada#27]
### 설명

- 특정 방 목록을 선택했을 때, 해당 방의 시공 상태로 이동하는 기능 추가

### 예상 작업 기간

~ 10/20 (목)

**Comment by ikanic** [comment]
Task 담당자가 미뉴에서 에디로 변경되었습니다.
이에 따라 Assignees에서 미뉴를 삭제하고 에디를 추가합니다.
