### ISSUE TITLE
[Bug] WorkingHistoryView및 ChipView 게시물이 2개뿐일 때, 컬렉션 뷰 스크롤이 안되어 버튼에 컨텐츠가 가려지는 버그

### ISSUE THREAD

**Issue by taek0622** [DeveloperAcademy-POSTECH/MacC-Team-Samsamhada#85]
### 설명

<img src="https://user-images.githubusercontent.com/81027256/198356307-9afecf86-b943-484a-94c6-3665e3891306.png" width=300>

- WorkingHistoryView에 게시물이 2개뿐일 때, 컬렉션 뷰 스크롤이 안되어 버튼에 컨텐츠가 가려지는 버그 발생

**Comment by JUNY0110** [comment]
태스크 납치했습니다.
